name: michaelachrisco2/ReadOnlyTraitLaravel/build
on:
  push:
    branches:
    - main
jobs:
  build_php_version:
    runs-on: ubuntu-latest
    container:
      image: php:8.0.20
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: php-actions/composer@master
      with:
        php_version: '8.1'
        ssh_key: ${{ secrets.SSH_KEY }}
        ssh_key_pub: ${{ secrets.SSH_KEY_PUB }}
    - run: composer self-update
    - run: composer install -n --prefer-dist --no-plugins
    - run: "./vendor/bin/kahlan -reporter=verbose"
  build_latest:
    runs-on: ubuntu-latest
    container:
      image: php:latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: php-actions/composer@master
      with:
        php_version: '8.1'
        ssh_key: ${{ secrets.SSH_KEY }}
        ssh_key_pub: ${{ secrets.SSH_KEY_PUB }}
    - run: composer self-update
    - run: composer install -n --prefer-dist --no-plugins
    - run: "./vendor/bin/kahlan -reporter=verbose"